-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 14:08:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mockdec23
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mockdec23` ;

-- -----------------------------------------------------
-- Schema mockdec23
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mockdec23` DEFAULT CHARACTER SET utf8 ;
USE `mockdec23` ;

-- -----------------------------------------------------
-- Table `mockdec23`.`use`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mockdec23`.`use` ;

CREATE TABLE IF NOT EXISTS `mockdec23`.`use` (
  `id` INT NOT NULL,
  `activity` VARCHAR(45) NULL,
  `sector` VARCHAR(45) NULL,
  `use` TEXT(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mockdec23`.`demographics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mockdec23`.`demographics` ;

CREATE TABLE IF NOT EXISTS `mockdec23`.`demographics` (
  `id` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  `region` VARCHAR(100) NULL,
  `borrower_genders` TEXT(400) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mockdec23`.`financials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mockdec23`.`financials` ;

CREATE TABLE IF NOT EXISTS `mockdec23`.`financials` (
  `id` INT NOT NULL,
  `funded_amount` FLOAT NULL,
  `currency` CHAR(4) NULL,
  `term_in_months` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mockdec23`.`campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mockdec23`.`campaign` ;

CREATE TABLE IF NOT EXISTS `mockdec23`.`campaign` (
  `id` INT NOT NULL,
  `posted_time` DATETIME NULL,
  `funded_time` DATETIME NULL,
  `lander_count` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_campaign_use`
    FOREIGN KEY (`id`)
    REFERENCES `mockdec23`.`use` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campaign_demographics1`
    FOREIGN KEY (`id`)
    REFERENCES `mockdec23`.`demographics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campaign_financials1`
    FOREIGN KEY (`id`)
    REFERENCES `mockdec23`.`financials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
